# Explicit ownership: a new Test_*.cpp must be assigned to one domain.
set(AYUI_TEST_GROUPS Controls Text Layout Interaction Docking Rendering LayoutAuthoring Packaging)

set(AYUI_TEST_Controls_SOURCES
    Test_Widget.cpp
    Test_Button.cpp
    Test_CheckBox.cpp
    Test_RadioButton.cpp
    Test_RadioGroup.cpp
    Test_Slider.cpp
    Test_ColorPicker.cpp
    Test_ProgressBar.cpp
    Test_ScrollBar.cpp
    Test_InteractiveWidget.cpp
    Test_Image.cpp
    Test_Style.cpp
    Test_Panel.cpp
    Test_ListView.cpp
    Test_TileView.cpp
    Test_ComboBox.cpp
    Test_TabControl.cpp
    Test_Separator.cpp
    Test_ToolBar.cpp
    Test_ToolBarSeparator.cpp
    Test_StatusBar.cpp
    Test_StatusBar_G8.cpp
    Test_TreeNode.cpp
    Test_TreeView.cpp
    Test_TabStrip.cpp
    Test_Style_G9.cpp
    Test_Theme_G11.cpp
    Test_UndoRedo_P1.cpp
    Test_Leak.cpp
    Test_Spinner.cpp
    Test_Productization.cpp
)

set(AYUI_TEST_Text_SOURCES
    Test_TextInput.cpp
    Test_TextLabel.cpp
    Test_I18n.cpp
    Test_TextArea.cpp
    Test_RichText.cpp
    Test_TextAreaMeasure.cpp
    Test_Clipboard.cpp
    Test_TextInput_Selection.cpp
    Test_TextStyle_Fields.cpp
    Test_TextAreaLifecycle.cpp
    Test_UnicodeText.cpp
)

set(AYUI_TEST_Layout_SOURCES
    Test_Thickness.cpp
    Test_Layout.cpp
    Test_WidgetFactory.cpp
    Test_LayoutLoader.cpp
    Test_Serializer.cpp
    Test_SerializerCompleteness.cpp
    Test_R6_CompoundWidget.cpp
    Test_R9_NamespaceEnum.cpp
    Test_GridPanel.cpp
    Test_Constraint_G13.cpp
    Test_DockAreaLoader.cpp
    Test_LayoutPersistence.cpp
    Test_ContainerContract.cpp
    Test_ScrollView.cpp
    Test_SyncVerticalBar.cpp
    Test_ContainerContract_Cut2.cpp
    Test_WidgetSerializer_AllTypes.cpp
    Test_AnchorLayout.cpp
    Test_UIFlow.cpp
)

set(AYUI_TEST_Interaction_SOURCES
    Test_Window.cpp
    Test_UIManager.cpp
    Test_SelectableWidget.cpp
    Test_Tooltip.cpp
    Test_MenuItem.cpp
    Test_Menu.cpp
    Test_MenuBar.cpp
    Test_Dimmer.cpp
    Test_Modal.cpp
    Test_ModalDialog.cpp
    Test_DragDrop.cpp
    Test_MenuShortcut_P3.cpp
    Test_UIManagerPerWindow.cpp
    Test_WindowResize.cpp
    Test_WheelRouting.cpp
    Test_TypeaheadBuffer.cpp
    Test_Scene_Suite_G.cpp
    Test_MenuBarLifecycle.cpp
    Test_DeviceInputBridge.cpp
)

set(AYUI_TEST_Docking_SOURCES
    Test_DockArea.cpp
    Test_DockFloat.cpp
    Test_CardPromotion.cpp
    Test_DockTabGroup.cpp
    Test_DockTree.cpp
)

set(AYUI_TEST_Rendering_SOURCES
    Test_B3RoundedFill.cpp
    Test_RenderBackend.cpp
    Test_MockBlendGradient.cpp
    Test_ImageTexture_G10.cpp
    Test_Theme_Gallery.cpp
    Test_OpacityAnimation.cpp
    Test_Tween.cpp
    Test_ColorAnimation.cpp
    Test_AnimationProductization.cpp
    Test_PopupFade.cpp
    Test_CardStyle_Render.cpp
    Test_DirtyRect.cpp
    Test_RetainedDisplayListLayer.cpp
    Test_GetWorldBoundsCache.cpp
)

set(AYUI_TEST_LayoutAuthoring_SOURCES
    Test_LayoutEditorCore.cpp
    Test_LayoutPublicationModel.cpp
)

set(AYUI_TEST_Packaging_SOURCES
    Test_UIAssetCollector.cpp
)
